load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
  name = "lexer",
  srcs = [
  "scanner.cc", 
  "token.cc",
  ],
  hdrs = [
  "scanner.hpp",
  "token.hpp",
  ],
  visibility = ["//main:__pkg__"],
)
